### ISSUE TITLE
new changes in db branch causing issues

### ISSUE THREAD

**Issue by kentywang** [kentywang/Agamari#96]
- chat message sometimes show up three times
- being eaten sometimes crashes the game for client
- sometimes no one can rejoin a room
- player moves too fast and bounces off to orbit
- console shows cannot read property 'nickname' of undefined

I will try and find how to reproduce these issues, but they seem to be introduced with the db changes

**Comment by tomjschuster** [comment]
I'm pretty sure most of these issues are due deployed db not being seeded/set up correctly. I'll try to deploy to dev again and debug.

**Comment by quirkycorgi** [comment]
I merged your changes into master, and pushed the build to dev heroku. 

One issue I found was that I got "You left [object object]'s orbit" when leaving orbit.
